# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d9a2d9c28f719c9efe931e86450d5e4c116d83ea89277405cba6442ec6b3058eb8f74840e305cb9b9f1378da3f03877e895cf1bbb7c0d90f93082dc8f2b6038

test:
  secret_key_base: 777d850be98b3c08a2f8018c8425ff194fb921ae48da92037643759dfa42c51f6e9903f1810c9da473008677b8ea3a5fcb4444f52b94560abed69c2fe9fd6026

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
